sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: user_center
    username: root
    password: tiancheng

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
